const fruitData = [
    'Acai', 
    'Aceola',
    'Apple',
    'Apricot',
    'Avocado',
    'Banana',
    'Blackberry',
    'Blueberry',
    'Camu Camu',
    'Cherry',
    'Clementine',
    'Coconut',
    'Cranberry',
    'Cucumber',
    'Currant',
    'Date',
    'Durian',
    'Fig',
    'Goji berry',
    'Gooseberry',
    'Grapefruit',
    'Grape',
    'Jackfruit',
    'Kiwi',
    'Kumquat',
    'Lemon',
    'Lime',
    'Lucuma',
    'Lychee',
    'Mango',
    'Mangosteen',
    'Melon',
    'Mulberry',
    'Nectarine',
    'Orange',
    'Papaya',
    'Passion Fruit',
    'Peach',
    'Pear',
    'Pineapple',
    'Plum',
    'Pomegranate',
    'Pomelo',
    'Prickly Pear',
    'Prune',
    'Raspberry',
    'Strawberry',
    'Tangerine',
    'Watermelon'
]

export default fruitData
